###Listar los movimientos
GET http://localhost:3000/api/movimientos

###Alta de movimiento
POST http://localhost:3000/api/movimientos
Content-Type: application/json

{
    "descripcion": "Beca Progresar",
    "monto": 30000,
    "fecha": "2025-07-13",
    "tipo": "INGRESO",
    "categoriaId": 5
}

### Modificar movimiento
PUT http://localhost:3000/api/movimientos/1
Content-Type: application/json

{
    "descripcion": "Beca Progresar",
    "monto": 30000,
    "fecha": "2025-07-13",
    "tipo": "INGRESO",
    "categoriaId": 5
}

### Eliminar movimiento
DELETE http://localhost:3000/api/movimientos/3

### Filtrar movimientos por tipo y fecha
GET http://localhost:3000/api/movimientos/filtrados?tipo=INGRESO&mes=2025-07

#### Listar métricas por categoría
GET http://localhost:3000/api/movimientos/metricas/categorias?tipo=EGRESO&mes=2025-07